@extends('layouts.app')
@section('title','NineEleven — Your Hair. Your Statement.')
@section('content')
<section class="hero"><div class="hero-bg"></div><div class="hero-copy"><p class="eyebrow">EST. 2024 · SAIGON</p><h1>YOUR HAIR.<br>YOUR <em>STATEMENT.</em></h1><p class="lead">Không chỉ là một mái tóc đẹp. Đó là cách bạn bước ra thế giới — tự tin, sắc nét, đúng chất riêng.</p><a class="btn" href="{{ route('booking.create') }}">CHỌN LỊCH CỦA BẠN <span>↗</span></a></div><div class="scroll-mark">SCROLL TO DISCOVER ↓</div></section>
<div class="ticker"><div>PRECISION CUT · REAL ATTITUDE · SAIGON CRAFT · PRECISION CUT · REAL ATTITUDE · SAIGON CRAFT ·</div></div>
<section class="intro" id="story"><p class="eyebrow">/ 01 — NINEELEVEN DNA</p><h2>CHÚNG TÔI KHÔNG<br>CHẠY THEO <span>XU HƯỚNG.</span><br>CHÚNG TÔI TẠO RA NÓ.</h2><div class="intro-note"><span class="line"></span><p>Mỗi đường kéo là một quyết định. Mỗi kiểu tóc là một tuyên ngôn. NineEleven kết hợp kỹ thuật barber chuẩn xác với thẩm mỹ đường phố đương đại.</p></div></section>
<section class="services" id="services"><div class="section-head"><div><p class="eyebrow">/ 02 — MENU</p><h2>DỊCH VỤ<br><em>SIGNATURE</em></h2></div><p>Thiết kế vừa đủ cho bạn.<br>Không rập khuôn. Không vội vàng.</p></div>
<div class="service-list">@foreach($services as $i => $service)<article><div class="service-no">0{{ $i+1 }}</div><div><h3>{{ $service->name }}</h3><p>{{ $service->description }}</p></div><div class="service-meta"><strong>{{ number_format($service->price/1000) }}K</strong><span>{{ $service->duration }} PHÚT</span></div><a href="{{ route('booking.create',['service'=>$service->id]) }}">↗</a></article>@endforeach</div></section>
<section class="manifesto"><div class="manifesto-word">NINE<br><span>ELEVEN</span></div><div class="manifesto-copy"><p class="eyebrow">NO COPY. JUST CHARACTER.</p><blockquote>“THE BEST HAIRCUT IS THE ONE THAT FEELS LIKE <em>YOU.</em>”</blockquote></div></section>
<section class="artists" id="artists"><div class="section-head"><div><p class="eyebrow">/ 03 — THE CREW</p><h2>GẶP NHỮNG<br><em>NGƯỜI THỢ</em></h2></div><p>Kỹ thuật là nền tảng.<br>Lắng nghe mới tạo nên khác biệt.</p></div><div class="artist-grid">@foreach($barbers as $i => $barber)<article class="artist-card artist-{{ $i+1 }}"><div class="artist-art"><span>0{{ $i+1 }}</span></div><h3>{{ $barber->name }}</h3><p>{{ $barber->title }}</p></article>@endforeach</div></section>
<section class="cta"><p class="eyebrow">SẴN SÀNG CHO DIỆN MẠO MỚI?</p><h2>YOUR NEXT LOOK<br>STARTS <em>HERE.</em></h2><a class="btn btn-light" href="{{ route('booking.create') }}">ĐẶT LỊCH NGAY <span>↗</span></a></section>
@endsection
